version: 1.{build}
branches:
  except:
  - gh-pages
image: Visual Studio 2017
clone_depth: 1
init:
- cmd: git config --global core.autocrlf true
install:
- cmd: >-
    set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%

    pip3 install "sphinx==1.8.2"
build_script:
- cmd: >-
    set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%

    set CI_HASH=%APPVEYOR_REPO_COMMIT:~0,7%

    cd %APPVEYOR_BUILD_FOLDER%

    mkdir results

    call make.bat html

    call make.bat htmlhelp

    "%ProgramFiles(x86)%\HTML Help Workshop\hhc.exe" build\htmlhelp\fedora-faq-ru.hhp && exit /b 1 || exit /b 0

    move build\htmlhelp\fedora-faq-ru.chm results\fedora-faq-ru.chm

    7z a -m0=LZMA2 -mx9 -t7z results\faq_html_%CI_HASH%.7z %APPVEYOR_BUILD_FOLDER%\build\html\*
artifacts:
- path: results\*.chm
  name: chm
- path: results\*.7z
  name: html
